### ISSUE TITLE
opendkim dkim

### ISSUE THREAD

**Issue by davordragic** [wader/postfix-relay#78]
I having issue with dkim configuration.
Certificates were generated automaticly and save into pv.
But on start of docker image, I see error
`opendkim: /etc/opendkim.conf: configuration error at line 2: unrecognized parameter`

My /etc/opendkim.conf is generated and looks like:
```
InternalHosts 0.0.0.0/0, ::/0
KEY_TABLE vps._domainkey.mydomain.com:default:/etc/opendkim/keys/mydomain.com/vps.private
KeyTable refile:/etc/opendkim/KeyTable
Mode sv
SELECTOR vps
SigningTable refile:/etc/opendkim/SigningTable
Socket inet:12301@localhost
Syslog yes
UMask 002 
```
docker-compose.yml file is like this: 
```
yaml
  postfix:
    image: mwader/postfix-relay
    restart: unless-stopped
    volumes:
      - ./env/postfix/dkim/:/etc/opendkim/keys/
    environment:
      - POSTFIX_myhostname=${HOSTNAME}
      - OPENDKIM_DOMAINS=mydomain.com=vps
      - OPENDKIM_SELECTOR=vps
      - OPENDKIM_KEY_TABLE=vps._domainkey.mydomain.com:default:/etc/opendkim/keys/mydomain.com/vps.private
```
** I have replaced my actual domain with mydomain.com **

Main issue here is that my email don't have DKIM signature.

I have tested it via https://dkimvalidator.com/ and results is: This message does not contain a DKIM Signature
```
Received: from **hostname** (**ip**.clients.your-server.de [**ip**])
	by relay-2.us-west-2.relay-prod (Postfix) with ESMTPS id 2CD3C2501A
	for <SipMBRRfppi4kt@dkimvalidator.com>; Tue,  9 May 2023 14:53:28 +0000 (UTC)
Received: from **domain** (**hostname**_default [172.0.0.5])
	by **hostname** (Postfix) with ESMTP id B5275E001D
	for <SipMBRRfppi4kt@dkimvalidator.com>; Tue,  9 May 2023 14:53:26 +0000 (UTC)
Date: Tue, 9 May 2023 14:53:26 +0000
To: SipMBRRfppi4kt@dkimvalidator.com
From: =?UTF-8?Q?=5B**hostname**?= <develop@**domain**>
Subject: =?UTF-8?Q?[**hostname**]_Ponastavi_geslo?=
Message-ID: <4T8O2u99oCNsamVrGrcmvqxJYSUNFYnobuoKPbMq7o@**domain**>
X-Mailer: WPMailSMTP/Mailer/smtp 3.7.0
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

**email content**
```

What am I missing here?

**Comment by wader** [comment]
Hmm could it be as simple as `OPENDKIM_KEY_TABLE` should be `OPENDKIM_KeyTable`? Maybe also `OPENDKIM_ Selector`. It's a bit confusing `OPENDKIM_DOMAINS` is treated differently, all the other gets written as is to config.

**Comment by davordragic** [comment]
Thank you for fast response. I have changed the line in docker-compose.yml
```
 postfix:
    image: mwader/postfix-relay
    restart: unless-stopped
    volumes:
      - ./env/postfix/dkim/:/etc/opendkim/keys/
    environment:
      - POSTFIX_myhostname=${HOSTNAME}
      - OPENDKIM_DOMAINS=kogovsek.si=vps
      - OPENDKIM_SELECTOR=vps
      - OPENDKIM_KeyTable=vps._domainkey.kogovsek.si:default:/etc/opendkim/keys/kogovsek.si/vps.private
```
Now I get new error: 
```
$ docker compose logs -f postfix
**hostname**-postfix-1  | DNS records:
**hostname**-postfix-1  | vps._domainkey	IN	TXT	( "v=DKIM1; h=sha256; k=rsa; p=******" )
**hostname**-postfix-1  | opendkim: /etc/opendkim.conf: vps._domainkey.mydomain.com:default:/etc/opendkim/keys/mydomain.com/vps.private: dkimf_db_open(): Unknown database type
**hostname**-postfix-1  | Starting OpenDKIM: Starting Postfix Mail Transport Agent: postfix.
**hostname**-postfix-1  | 2023-05-09T15:06:49.783629+00:00 47692a7af8a8 rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="141" x-info="https://www.rsyslog.com"] start
```

I'll do quick test if maybe DKIM signature is attached to email.
