### ISSUE TITLE
smtp relay with auth when client connect

### ISSUE THREAD

**Issue by wolf-skin** [wader/postfix-relay#79]
This is very flexible docker which I can config the postfix by environment variable.

However, I had a issue when use it. I want it to be a smtp relay which let some device to send me email because my device is very old and only allow SSL (no TLS) or plain text connection, so it cannot connect smtp of outlook or gmail. I decide to use this docker to get the email from my device and as a smtp relay to use smpt of outlook to send email to me. 
I cannot use NO AUTH option to relay my email because the old device must send login even empty the user and password,

After done the setup, I test it directly by telnet, after input ELHO {hostname}, I use AUTH LOGIN and input "Y2FtCg==" "Y2FtCg==" (user/password as cam/cam which encode by base64) but the result is "535 5.7.8 Error: authentication failed: authentication failure", the log show "SASL login authentication failed". I try to use testsaslauthd from docker console, but still has authentication fail message.
I still not setup relay part, just test the device can connect this docker and submit email to it only.
Following is the docker-compose.yml and passwd_file
docker-compose.yml
```
version: "2"
  #use hostname "smtp" as SMTP server
  smtp:
    container_name: "postfix-relay"
    image: mwader/postfix-relay:latest
    restart: always
    ports:
    - "10025:25"
    volumes:
    - /srv/docker_data/smtp-relay/passwd_file:/etc/postfix/sasl/sasl_passwds
    - /srv/docker_data/smtp-relay/mwader/postfix-relay/log:/var/log/
    environment:
    - TZ=Asia/Hong_Kong
    - SASL_Passwds=/etc/postfix/sasl/sasl_passwds
    - POSTFIX_cyrus_sasl_config_path=/etc/postfix/sasl
    - POSTFIX_myhostname=naspi.local
    - POSTFIX_smtpd_sasl_local_domain=$myhostname
    - POSTFIX_smtpd_sasl_auth_enable=yes
    - POSTFIX_broken_sasl_auth_clients=yes
    - POSTFIX_smtpd_sasl_security_options=noanonymous
    - POSTFIX_smtpd_recipient_restrictions="permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination"
    #- OPENDKIM_DOMAINS=naspi.local
    #- POSTFIX_smtpd_tls_security_level=may
    #- POSTFIX_relayhost=[smtp-mail.outlook.com]:587
    #- POSTFIX_smtpd_use_tls=yes
    #- POSTFIX_smtpd_recipient_restrictions="permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination"
    - RSYSLOG_LOG_TO_FILE=yes
    - RSYSLOG_TIMESTAMP=yes
```

passwd_file
`cam:$6$.CbOgrN4xn.RB$sOZo8mHHuFi79OvHYVJlDN51YFmcBeVi1BhlC3fUiuBItHVOXkUcfH.ZZEZ0m37nkPtYPI8y3TGW7SISKj9/u0`

Would you help me. Thanks!
