### ISSUE TITLE
Run as different user than root?

### ISSUE THREAD

**Issue by Tofandel** [wader/postfix-relay#89]
I run docker compose as an user other than root and to avoid filesystem permissions issues on my mounted files I change the user and group id to match the user running docker

```
smtp:
        image: mwader/postfix-relay
        restart: always
        user: 1000:1000
        volumes:
            -  ./data/dkim:/etc/opendkim/keys
```

Unfortunately the image fails to run with another user than root `/bin/bash: /root/run: Permission denied`
